# Generated by Django 6.0.5 on 2026-05-13 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='mode',
            field=models.CharField(choices=[('truck', 'Company Truck'), ('car', 'Company Car'), ('boda', 'Boda Boda'), ('matatu', 'Matatu / Bus')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('field_operations', '🚛 Field Operations'), ('processing_plant', '🏭 Processing Plant'), ('water_sanitation', '💧 Water & Sanitation'), ('waste_management', '♻️ Waste Management'), ('manager', '👨\u200d💼 Sanergy Manager')], default='field_operations', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
